#if !canImport(ObjectiveC)
import XCTest

extension TelesignRequestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TelesignRequestTests = [
        ("testGenerateHeaders", testGenerateHeaders),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TelesignRequestTests.__allTests__TelesignRequestTests),
    ]
}
#endif
