//
//  ScoreResponse.swift
//  Telesign
//
//  Created by Andrew Edwards on 7/25/17.
//
//

public struct TelesignScoreResponse: TelesignModel {
    /// A 32-digit hex value used to identify the web service request. The value is unique to each web service request, is randomly-generated by TeleSign, and is returned in the response message immediately following the web service request.
    public var referenceId: String
    /// An object that describes the status of your transaction.
    public var status: Status
    /// An object containing details about the numbering attributes of the specified phone number.
    public var numbering: Numbering
    /// An object containing details about the phone type.
    public var phoneType: PhoneType
    /// /// An object containing geographical location information associated with the phone number.
    public var location: Location
    /// An object that describes the risk score for the phone number specified in the request.
    public var risk: Risk
    /// An object containing information about the company that provides telecommunications services for the phone number.
    public var carrier: Carrier
}

// MARK: Numbering
public struct Numbering: TelesignModel {
    /// An object containing details about the original phone number passed to TeleSign's PhoneID API.
    public var original: Original
    /// An object containing details about how the phone number was cleansed. Phone cleansing corrects common formatting issues in submitted phone numbers.
    public var cleansing: Cleansing
}

// MARK: Original
public struct Original: TelesignModel {
    /// The base phone number prefixed with the country dialing code.
    public var completePhoneNumber: String
    /// A 1, 2, or 3-digit number representing the country dialing code. For example, the country dialing code for both the U.S.A. and Canada is 1, and the country dialing code for the United Kingdom is 44.
    public var countryCode: String
    /// The base phone number. This is simply the phone number without the country dialing code.
    public var phoneNumber: String
}

// MARK: Cleansing
public struct Cleansing: TelesignModel {
    /// An object containing cleansing details about a phone number used for receiving voice calls.
    public var call: Call
    /// An object containing cleansing details about a phone number used for receiving text messages.
    public var sms: SMS
}

// MARK: Call
public struct Call: TelesignModel {
    /// A 1, 2, or 3-digit number representing the country dialing code. For example, the country dialing code for both the U.S.A. and Canada is 1, and the country dialing code for the United Kingdom is 44.
    public var countryCode: String
    /// The base phone number. This is simply the phone number without the country dialing code.
    public var phoneNumber: String
    /// One of the phone number cleansing codes describing the cleansing operation TeleSign performed on the phone number. The default value is 100 (No changes were made to the phone number).
    public var cleansedCode: Int
    /// The minimum number of digits allowed for phone numbers with this particular country dialing code.
    public var minLength: Int
    /// The maximum number of digits allowed for phone numbers with this particular country dialing code.
    public var maxLength: Int
}

// MARK: SMS
public struct SMS: TelesignModel {
    /// A 1, 2, or 3-digit number representing the country dialing code. For example, the country dialing code for both the U.S.A. and Canada is 1, and the country dialing code for the United Kingdom is 44.
    public var countryCode: String
    /// The base phone number. This is simply the phone number without the country dialing code.
    public var phoneNumber: String
    /// One of the phone number cleansing codes describing the cleansing operation TeleSign performed on the phone number. The default value is 100 (No changes were made to the phone number).
    public var cleansedCode: Int
    /// The minimum number of digits allowed for phone numbers with this particular country dialing code.
    public var minLength: Int
    /// The maximum number of digits allowed for phone numbers with this particular country dialing code.
    public var maxLength: Int
}

// MARK: Phonetype
public struct PhoneType: TelesignModel {
    /// One of the phone type codes.
    public var code: String
    /// Text describing the phone type.
    public var description: String
}

// MARK: Location
public struct Location: TelesignModel {
    /// A string specifying the name of the city associated with the phone number.
    public var city: String
    /// A string specifying the name of the County (or Parish) associated with the phone number (U.S. only).
    public var county: String?
    /// The 2-letter state abbreviation code of the state (province, district, or territory) associated with the phone number (North America only).
    public var state: String?
    /// The 5-digit United States Postal Service ZIP Code associated with the phone number (U.S. only).
    public var zip: String?
    /// A 4-digit string indicating the Primary Metropolitan Statistical Area (PMSA) code for the location associated with the phone number (U.S. only).
    public var metroCode: String?
    /// An object containing details about the country associated with the phone number.
    public var country: Country
    /// An object containing details about the time zone associated with the phone number.
    public var timeZone: Timezone
    /// An object containing details about the geographical coordinates of the location where the phone number is registered.
    public var coordinates: Coordinates
}

// MARK: Country
public struct Country: TelesignModel {
    /// The country name associated with phone number.
    public var name: String
    /// The ISO 3166-1 2-letter country code associated with the phone number.
    public var iso2: String
    /// The ISO 3166-1 3-letter country code associated with the phone number.
    public var iso3: String
}

// MARK: Timezone
public struct Timezone: TelesignModel {
    /// A string identifying the Time Zone Name (TZ) associated with the phone number (U.S. only). For example: “America/Los_Angeles”.
    public var name: String?
    /// For U.S. domestic phone numbers, this parameter returns the UTC offset associated with the phone number. For international phone numbers, this parameter returns the minimum UTC offset for the country associated with the phone number.
    public var utcOffsetMin: String
    /// For international phone numbers, this parameter returns the maximum UTC offset for the country associated with the phone number. For U.S. domestic phone numbers, this parameter returns the same result as utc_offset_min.
    public var utcOffsetMax: String
}

// MARK: Coordinates
public struct Coordinates: TelesignModel {
    /// A value indicating the number of degrees of latitude of the location associated with the phone number, expressed in seven decimal digits, with five decimal places. For example, 34.18264.
    public var latitude: Double?
    /// A value indicating the number of degrees of longitude of the location associated with the phone number, expressed in eight decimal digits, with five decimal places For example, -118.30840.
    public var longitude: Double?
}

// MARK: Risk
public struct Risk: TelesignModel {
    /// A string indicating the severity of the risk.
    public var level: String
    /// A string indicating the action that TeleSign recommends that you take based on the risk score.
    public var recommendation: String
    /// One of the scores and risk levels values.
    public var score: Int
}

// MARK: Carrier
public struct Carrier: TelesignModel {
    /// A string specifying the name of the carrier. For example: “Verizon”.
    public var name: String
}
